### ISSUE TITLE
Add support for populating java.net.URL and java.net.URI types

### ISSUE THREAD

**Issue by ltoinel** [benas/jPopulator#22]
Hi,

I have some error with private fields ... Any idea ?

Grave: Unable to populate an instance of type class java.net.URI
java.lang.IllegalAccessException: Class io.github.benas.jpopulator.impl.PopulatorImpl can not access a member of class java.net.URI with modifiers "private"

Thank-you

Regards,

**Comment by benas** [comment]
Hi Ludovic,

Thank you for pointing out this issue.

The generation of random values for type `java.net.URI` is not supported yet. jPopulator cannot generate random instances of URIs. Please refer to the [documentation](https://github.com/benas/jPopulator/wiki/Supported-types) for supported types as of current version.

I'll plan to add support for `java.net.URI` and `java.net.URL` for next release (That will be released shortly by the way, stay tuned). Any contribution is welcome :-)

Regards
Mahmoud

**Comment by ltoinel** [comment]
Thank-you Mahmoud ! 
It should be excellent to catch the IllegalAccessException in the PopulatorImpl : 

            try{
            	  result = type.newInstance();
            } catch (IllegalAccessException i){
                 if (allowNotSupported){
                 	return null; // To avoid to block the process
                  } else {
                       throw i;
                 }
            }

**Comment by benas** [comment]
Actually the process is not blocked. The field for which jPopulator cannot generate a random value will be set to null, but other fields will be populated as expected.

I've  just added a test case for this issue here : 1511aa769078f63a34690b5008f6c31279142d69

The name of the website is populated, but not its url not its uri (they are set to null since their types are not supported yet). This should be fixed once the support for `java.net` types will be added.

But as you said, it should be better to catch specific exception (IllegalAccessException) rather than the generic one (Exception) and improve the log message:

`Grave: Unable to populate an instance of type class java.net.URI` does not say that the type is not supported, it would be better to say it explicitly to the user.

**Comment by benas** [comment]
Hi Ludovic,

I have added support for populating `java.net.URI` and `java.net.URL` types and deployed the version 1.2.0-SNAPSHOT to [maven central](https://oss.sonatype.org/content/repositories/snapshots/io/github/benas/jpopulator/1.2.0-SNAPSHOT/).

Could you please try to populate your bean with this version and keep me informed if you get the same exception reported above?

Many thanks upfront.

Regards
Mahmoud

**Comment by benas** [comment]
Hi Ludovic,

The fix for this issue has been released in version 1.2.0.

Do not hesitate to report any problem if any. 

Regards
Mahmoud
